### ISSUE TITLE
Error: "command 'mocha-maty.refreshExplorer' not found" when trying to refresh the sidebar

### ISSUE THREAD

**Issue by A-Gochnio** [maty21/mocha-sidebar#1]
Hi,

VS Code shows an error `command 'mocha-maty.refreshExplorer' not found` when trying to refresh the sidebar. No tests are being shown, despite having some in `test/` directory.
I've got mocha installed both globally and locally, in node_modules.
The same error was present when I only had it installed locally.

**Comment by maty21** [comment]
I know Ill fix this soon sry

**Comment by maty21** [comment]
fixed in version 0.4.0

**Comment by balexandre** [comment]
VSCode 1.22.2, extension version 0.17.5

just go the same issue... mocha installed locally and globally (5.1.0)

[![](https://s6.postimg.cc/ijscc6xbj/screenshot_188.png)](https://s6.postimg.cc/ijscc6xbj/screenshot_188.png)

**Comment by polkhovsky** [comment]
Hello from 2021. Mocha 8.3.0, extension version 0.22.2, VSCode 1.55.2 and I get the same message.

**Comment by balexandre** [comment]
@polkhovsky unfortunately I had to drop this extension in favor of [another mocha test explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) and since I never looked back
