### ISSUE TITLE
Mocha Debug and Report Options

### ISSUE THREAD

**Issue by osvaldo-github** [maty21/mocha-sidebar#10]
Hi, I have two questions about the mocha sidebar options.

1. When I run this command at the Windows prompt, this works perfectly:
npm mocha --ui bdd - reporter mocha-simple-html-reporter - reporter-output options = report.html

Ok, but when I use the mocha-sidebar in VS Code

Open User Settings:
File -> Preferences -> Settings (VS Code)

{
"mocha.options": {
"ui": "bdd",
"reporter": "mocha-simple-html-reporter"
}
}

ok, but how to configure "--reporter-options output = report.html"?

2. When I run this command at the Windows prompt, this works perfectly:
npm mocha --debug-brk

Ok, but when I use mocha-sidebar in VS Code

Open User Settings:
File -> Preferences -> Settings (VS Code)

{
"mocha.node_options": [
"debug"
]
}

Ok, there another option to configure "--debug-brk"?

Thanks for the advance.

**Comment by yehiyam** [comment]
Hi
1. Mocha sidebar is using a custom reporter in order to capture the results and display them. So, unfortunately it is not possible to override the reporter. 
2. We have plans to support debugging in the future. It is not currently supported

**Comment by osvaldo-github** [comment]
Thank you very much for the quick response.
