### ISSUE TITLE
.only keyword is not restricting the debugged tests

### ISSUE THREAD

**Issue by linvi** [maty21/mocha-sidebar#104]
### Description

`.only` parameter is not applied when starting in debug mode.
`.skip` is working though but I need to add `.skip` to all the test suites that I do not wish to be debugged.

#### Steps to Reproduce

1. Create a `describe` test suite with multiple tests
2. Add a `it.only` to select one unique test to run within the suite.
3. Click the `debug item`

#### Expected Results

Only the `.only` test is run.

#### Actual Results

All the tests of the suite are being run.

#### Settings file

``` json
{
    "mocha.files.glob": "tst/**/*.js",
}
```

### Versions

- VScode: v1.23.1
- Mocha SideBar: v0.19.0
- Node Version: v6.14.1

### OS version

- [ ] Linux  (NOT TESTED)
- [X] Mac
- [ ] Windows (NOT TESTED)

**Comment by maty21** [comment]
you don't need to use it that way mocha sidebar allows you to debug specific file via sidebar by clicking on the bug icon or via lens

**Comment by maty21** [comment]
im closing it for now since its not an issue if i missed something feel free to reopen it tks
