### ISSUE TITLE
mocha.files.glob shold be an array

### ISSUE THREAD

**Issue by zhaochy1990** [maty21/mocha-sidebar#110]
### Description

mocha.files.glob shold be an array to contain a list a patterns.

for instance, sometimes we want both 'test/\*\*/*.test.js' and 'test/\*\*/*.spec.js'

#### Settings file

<!-- Example: {
```
  "mocha.files.glob": "test/**/*.js",
  "mocha.sideBarOptions": {
      "lens": true,
      "decoration": true,
      "autoUpdateTime": 2000,
      "showDebugTestStatus": true
  }
}
``` -->
```
```


### Versions

- VScode: vX.X.X
- Mocha SideBar: vX.X.X 
- Node Version: vX.X.X


### OS version
<!-- Check all that apply -->
- [ ] Linux 
- [ ] Mac
- [ ] Windows



#### Example for reproducing
<!-- path for github project -->
<!-- https://github.com/maty21/mocha-sidebar/tree/master/test/workspace -->
<!-- ...or provide your own repro URL -->

**Comment by maty21** [comment]
It's hard to implement coz if I remember correctly mocha can get only one arg as  a glob pattern
I believe that it will be better to ask mocha  for these feature . Than I will be happy to change mocha settings

**Comment by maty21** [comment]
I close it but if you can find a way to tell mocha how to get multiple paths feel free to reopen it again

**Comment by somombo** [comment]
@maty21, I tried the following and it doesn't work.  Is that intentional? 
 ```json 
{ "mocha.files.glob": "*(test/**/.test.js|test/**/.spec.js)" }
``` 

Shouldn't it be working in the meantime since this is in the style suggested on the [node-glob](https://github.com/isaacs/node-glob) lib that mocha-sidebar uses for this sort of thing?

.

**Comment by jeffbski** [comment]
Seems like node-glob supports multiple like you have suggested or `+(pattern|pattern|pattern)`
