### ISSUE TITLE
Unescaped regex characters in grep for test name

### ISSUE THREAD

**Issue by mutech** [maty21/mocha-sidebar#112]
### Description
When using mocha.grep, you don't escape regexp characters.

#### Steps to Reproduce
1. Name a mocha test (describe/context/it) using any regex characters, f.e. a single '['
2. Run that test
#### Expected Results
The test should be executed

#### Actual Results
"Exception has occurred: Syntax Error

### Versions

- VScode: v1.24.1
- Mocha SideBar: v0.19.1 
- Node Version: v9.3.0

### OS version

- [ ] Linux 
- [x] Mac
- [ ] Windows

**Comment by yehiyam** [comment]
similar to #99

**Comment by mutech** [comment]
Thanks for fixing this! Cheers, Michael
