### ISSUE TITLE
Debugging doesn't work when there's a bracket or other special chars on test name like #$%^, etc (and/or doesn't stop on break point)

### ISSUE THREAD

**Issue by vit100** [maty21/mocha-sidebar#118]
### Description
 test debugging doesn't work if test name has '()' or other spec chars like $#&, etc. in it.

#### Steps to Reproduce

create simple test like this, with name having '()' in it.
describe('some test', function(){
 it('should do something in myFunction()',function(){
 let a =1;  // set breakpoint here.  this breakpoint is not hit if name of the test above has '()'..
}
}

Lens should show 2 items: run and debug.
Set breakpoint on line with let a = 1;
Start debugging, by clicking on debug in lens line
-->

#### Expected Results
debugger should start and stop on line where break point is

#### Actual Results
message shown similar to 
```
C:\Program Files\nodejs\node.exe --inspect-brk=20987 ..\..\..\..\Users\vit\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.11\node_modules\mocha\bin\_mocha test/**/*.js --grep '^express-bus unit tests xx yy zz$' 
Debugger listening on ws://127.0.0.1:20987/8c6802a4-bcf3-435d-b866-ae26238c50e5
  0 passing (2ms)
```

#### Settings file

 Example: {
```
 describe('some test', function(){
 it('should do something in ()',function(){
 let a =1;  // set breakpoint here.  this breakpoint is not hit if name of the test above has '()'..
}
}
``` 
```
```

### Versions

- VScode: 1.24.1
- Mocha SideBar: 0.20.11
- Node Version: v8.11.2

### OS version

- [ ] Linux 
- [ ] Mac
- [ X] Windows

**Comment by yehiyam** [comment]
fixed in #99 and #112
