### ISSUE TITLE
Popups a lot when TS compilation fails

### ISSUE THREAD

**Issue by HeavyStorm** [maty21/mocha-sidebar#120]
I'm using the sidebar with a TypeScript project. Everything seems to work fine when everything is ok.

When I break the code, mocha (ts-node) encounters a issue compiling it. The issue is reported back to me through a VSCode pop up (below). This keeps happening every few moments, which is annoying.

![image](https://user-images.githubusercontent.com/1890900/42114799-c0b03096-7bc6-11e8-9ed8-3739d08cf0df.png)

My config:

"mocha": "^5.2.0"
"typescript": "^2.8.1"

VSCode version:

![image](https://user-images.githubusercontent.com/1890900/42114641-1e1949f8-7bc6-11e8-9d95-3732acbc55ae.png)

**Comment by yehiyam** [comment]
There is a config for that. mocha. showErrorPopup
Check if it works for you

**Comment by geotry** [comment]
I have the same issue and I tried to set `mocha. showErrorPopup` to `false` but I keep having alerts about compilation failures.
