### ISSUE TITLE
ES6 module import doesn't work

### ISSUE THREAD

**Issue by lkurylo** [maty21/mocha-sidebar#123]
I have installed mocha-sidebar and added to the user settings following lines from the plugin homepage:
```
"mocha.options": {
        "compilers": {
            "js": "babel-register"
        }
    },
    "mocha.requires": [
        "babel-register",
        //"babel-core/register"
    ]
```
When I try to execute the test, I got:
```
c:\Users\lkurylo\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.12\node_modules\mocha\bin\_mocha:325
    if (mod[0] == '.') 
```
In the debugger I see the command that is executed:
`C:\Program Files\nodejs\node.exe --inspect-brk=18349 ..\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.12\node_modules\mocha\bin\_mocha test/**/*.js --grep '^tests test$' -r babel-register --compilers '[object Object]' `

The --compiler flag looks broken to me. Any idea? I'm struggling with this the entire day and can't find a solution. Looks like a bug.

Node version: 10.4.0
VSCode version: 1.24.1
mocha-sidebar version: 0.20.12
And this is on Windows (10)

**Comment by maty21** [comment]
Hi 
try to replace it to "js:babel-register" let me know if it's working for you

**Comment by lkurylo** [comment]
I tried to put it in compilers, then in requires and in both. Result is the same

**Comment by lkurylo** [comment]
This is what I see in the Output window after these two changes (adding js: prefix):
trying to searching for tests using these settings: 
```
trying to searching for tests using these settings: 

    mocha path: mocha
    test files location: test/**/*.js
    files to ignore: **/.git/**/*,**/node_modules/**/*
    environmets: {}
    requires: ["js:babel-register"]
    options:  {"compilers":{"js":"js:babel-register"}}


if you find anything wrong please change those default settings
```
There is no problem with locally installed mocha and run the tests by npm run test.
Is this possible to change the entire path for the searching for mocha executabe? I saw the mocha.path in docs but I probably can't set it properly.

**Comment by lkurylo** [comment]
I have removed the 'js:' prefixes and update VSC. Right now the tests are executed, but not in the debug mode. There is still the same error provided.

**Comment by maty21** [comment]
If yo could create sample project it will be great I'll debug it. and see
what is the correct settings

**Comment by lkurylo** [comment]
Sample project is here: https://1drv.ms/u/s!At2hi-qFGwGHjdMLlI7dMvn4V3rAOg
I've included the entire node_modules catalog.

**Comment by maty21** [comment]
Thanks

**Comment by lkurylo** [comment]
Any progress on this?

**Comment by maty21** [comment]
hi 
try mocha side-bar latest version with this configuration ``0.12.16``
 I tried your sample on my pc and it seems to be working now with this configuration
```js
    "mocha.files.glob": "./test/hellotest.js",
    "mocha.requires": [
        "babel-register"
    ]

```

let me know if you still have problems

**Comment by lkurylo** [comment]
After a quick check it looks like it is working properly.
