### ISSUE TITLE
After VS Code restart the mocha - side bar is not initialised

### ISSUE THREAD

**Issue by balazser** [maty21/mocha-sidebar#125]
### Description

After then the VS Code was reloaded, the unit test list becomes empty. When I close the program, then restart the whole it works again with the initialization of VS Code.

#### Steps to Reproduce
Example:

1. Open VS Code
2. Check unit tests are there
3. Press F1 then Restart VS Code
4. Sidebar and coverage is loaded, but there is no test in it

#### Expected Results
Unit tests should be there

#### Actual Results
Unit tests should appear on the sidebar

#### Settings file

```
 "mocha.files.glob": "**/*.spec.js",
  "mocha.options": {
    "grep": "#integration",
    "invert": true,
  },
```

### Versions

- VScode: v1.25
- Mocha SideBar: v0.20.12 
- Node Version: v8.11.3

### OS version

- [ ] Linux 
- [x] Mac
- [ ] Windows

**Comment by eramitmittal** [comment]
I briefly looked at it and it seems a VS code issue. VS code does not callback the extension to get the tree to be shown. Workaround is to not have test view open when VS code is restarted.

**Comment by maty21** [comment]
Tks so I'm closing it if it's still an issue feel free to reopen it
