### ISSUE TITLE
Failed tests do not turn red if failure occurs in Mocha hooks

### ISSUE THREAD

**Issue by rosesonfire** [maty21/mocha-sidebar#15]
When an assertion fails in one of the **Mocha hooks** like **before**, **beforeEach** or **afterEach**, the corresponding test entry in the **moca-sidebar** **does not turn red**. Example:

<pre>describe("some test", () => {

  before(() => {
    // this assertion fails, but mocha-sidebar test entry does not turn red
    assert.equal(1, 2);
  });

  it("should pass", () => {

  });

});</pre>

**Comment by maty21** [comment]
hi @rosesonfire  
let me konw if @yehiyam  fixes in 0.12.0 solves this issue tks  :smile:

**Comment by rosesonfire** [comment]
@maty21 the fix works nicely for the pre-test-hooks like **before** and **beforeEach**. However the test entries do not turn red when the test fails in the post-test-hooks like **after** and **afterEach**.

Example code:
<pre>describe("some test", () => {
  
  after(() => {
    // this assertion fails, but mocha-sidebar test entry does not turn red
    assert.equal(1, 2);
  });

  it("should pass", () => {

  });

});</pre>

**Comment by yehiyam** [comment]
@roseonfire thanks for your report. The reason that the test turn green is that they do pass. The assertion happens only after the tests run. We could think of a way to indicate this in the UI.
As a side note, what is your use case? Are you asserting in the hooks?

**Comment by rosesonfire** [comment]
@yehiyam yes, there should be some way to indicate it in the UI. That is the whole point of using the extension, so that I don't have to run the command line every time, and yet expect the same outcome as the command line.

Yes, I have to do generic sinon mock verifications in aftereach hooks.

**Comment by yehiyam** [comment]
I'm closing this issue and opening a new one for the after hook.
I don't believe it is good practice to assert in the hooks, but maybe your use case merits it.
