### ISSUE TITLE
location of run options in test source

### ISSUE THREAD

**Issue by cyrfer** [maty21/mocha-sidebar#16]
The run/debug option that appears in the test source code is appearing in the wrong place. It works, but it shows on the wrong `it`. See the attached image, the upper `it` has 2x run options, and the lower `it` has NO run options.

![image](https://user-images.githubusercontent.com/4392990/32467560-e7725c0c-c2ff-11e7-9f3d-9f2bb6e26fc2.png)

**Comment by maty21** [comment]
the bug is that i have two test names under the same file the workaround until i fix it is to change the name for one of them even by adding space 

tks :)

**Comment by maty21** [comment]
fixed for version 0.13.2
commit  [fix lens](https://github.com/maty21/mocha-sidebar/commit/1a3ebbf501f612536bdacb71193ba6bb1ab35357)
