### ISSUE TITLE
mocha.env setting is ignored when running coverage

### ISSUE THREAD

**Issue by BePo65** [maty21/mocha-sidebar#160]
### Description
running tests with coverage enabled ignores environment variables defined in setting 'mocha.env'

#### Steps to Reproduce
Use my demo project from 'https://github.com/BePo65/MochaSidebarCoverWithEnv'

1. Open mocha-sidebar in VScode sidebar
2. use button "run all tests" (see image 'Step 2 from issue.png' in folder documentation of demo project)
3. test 'Read env variable set by mocha.env.DB_PORT' is green (see image 'ScreenshotWithoutCoverage.png' in folder documentation of demo project)
4. use button "Click for coverage" (see image 'Step 4 from issue.png' in folder documentation of demo project)
5. test 'Read env variable set by mocha.env.DB_PORT' is red (see image 'ScreenshotWithCoverage.png' in folder documentation of demo project)

#### Expected Results
coverage should also be setting environment variables from setting 'mocha.env'

#### Actual Results
looks like coverage is not setting environment variables from setting 'mocha.env'

#### Settings file

 "mocha.env": {
    "DB_PORT": 13300
  },
    "mocha.files.glob": "src/**/*.spec.js",
    "mocha.requires": [ ],
    "mocha.coverage": {
        "enable": true,
        "decoration": true,
        "runWithInterval": false,
        "autoUpdateInterval": 20000,
        "activeOnStart": false,
        "runAfterTest": false,
        "runCoverageAfterFileSave": false,
        "reporters": []
    }

### Versions

- VScode: v1.29.1
- Mocha SideBar: v0.20.20 
- Node Version: v10.13.0

### OS version
- [ ] Linux 
- [ ] Mac
- [X ] Windows 10

#### Example for reproducing

https://github.com/BePo65/MochaSidebarCoverWithEnv

**Comment by mauron85** [comment]
Same issue. Probably I will take look on this one.

**Comment by Jack-Works** [comment]
Same issue. And it doen't read mocha.opts either

**Comment by BePo65** [comment]
Cannot reproduce error by now (2020-06-17) with version 0.22.2 (from visual studio markedplace; strangely enough this repository has no release 0.22.2).
Therefore closing this issue.
