### ISSUE TITLE
mocha-sidebar empty upon startup

### ISSUE THREAD

**Issue by ThatBrianDude** [maty21/mocha-sidebar#18]
Sometimes (not always) when I open vscode absolutely  no tests show up in the sidebar. Clicking the refresh button does not help either.

After restarting vscode they show up again.

**Comment by maty21** [comment]
ok tks ill check it

**Comment by ThatBrianDude** [comment]
Actually the exact situation was this: 

I had to update nodejs as the code that was being tested didnt allow for async operations. 
After updating, the code was able to run without failures (previously I got the "unexpected token function" error due to having node 6 installed). 
Only then did mocha-sidebar fail to refresh the test suites. Not exactly sure what was going on but thats when the refresh didnt work. But honestly I dont even know if the tests were even running or not. 
I will be sure to post any update if I come across this again.

**Comment by rosesonfire** [comment]
I am using **node v8.5.0**. I have the same problem. The following workaround works for me.

**How to reproduce:**
1. Close all open files in VScode.
2. Exit VScode
3. Re-open VScode. At this point the tests should be loaded into the Mocha Sidebar, but they are not. Refreshing the Mocha Sidebar doesn't load them either.

**Work-around:**
1. Open a file in VScode (any file in your project)
2. Exit VScode
3. Re-open VScode. The tests are loaded into the Mocha Sidebar. So apparently you have to have some file(s) already open in VScode, when VScode starts.

**Comment by maty21** [comment]
Ok I'll check it @rosesonfire tks for your contribution :)
