### ISSUE TITLE
[Feature Request] Add support for TypeScript tests

### ISSUE THREAD

**Issue by pumano** [maty21/mocha-sidebar#35]
I use Mocha + TypeScript + Spectron/WebdriverIO for e2e testing. It's will be good to add support .ts/tsx files using mocha register ts-node

**Comment by maty21** [comment]
Hi 
did you tried the documentation about ts in the q&a section in the readme ?
There is specific section about using Typescript
Try it and if it not works for you tell me tks

**Comment by maty21** [comment]
Please reopen if it still an issue
