### ISSUE TITLE
Is it possible to support color output as mocha outputed in command line?

### ISSUE THREAD

**Issue by chigix** [maty21/mocha-sidebar#40]

**Comment by maty21** [comment]
hi  
we supporting it on the fly  you can set colors by adding the relevant arguments for it 
unfortunately its seem to be vscode issue [https://github.com/Microsoft/vscode/issues/243](https://github.com/Microsoft/vscode/issues/243) 

so I'm closing it for now.
 feel free to reopen it if you think that is still mocha side bar issue
