### ISSUE TITLE
"Invalid regular expression" error with test names ending in ?

### ISSUE THREAD

**Issue by kendfrey** [maty21/mocha-sidebar#41]
### Steps to reproduce:

- Create a test named "foobar?".
- Refresh the mocha sidebar.

### Result:

> Invalid regular expression: /foobar?+/: Nothing to repeat

Nothing loads.

### Diagnosis:

https://github.com/maty21/mocha-sidebar/blob/88f04f5d054b32704a23c94d0fb1d67cfcd3acf6/provider-extensions/NavigateEditorItem.js#L7

I think the problem is that test names should be treated as plain text, not regexes.

**Comment by kendfrey** [comment]
Proposed PR: #42

**Comment by maty21** [comment]
tks for your contribution
