### ISSUE TITLE
How to run tests that are dependent on root level hooks(before and after)

### ISSUE THREAD

**Issue by thyagab** [maty21/mocha-sidebar#43]
We are having root level before and after in file a.js to initialize global variables. 
we have our tests in b.js. In order to run one of our tests in b.js, we need before and after in a.js to run. How do we configure mocha-sidebar/mocha to run a.js before starting test in b.js.

**Comment by maty21** [comment]
How you run it via command line ?

**Comment by thyagab** [comment]
would be running the normal way. I upgraded the extension today and it seems to be working.

**Comment by cpamp** [comment]
Is this configurable? Right now I pass the root hook file before the glob in the command line. It works if I require the hook file in the test file but I'd prefer a configurable option.
