### ISSUE TITLE
Is it possible to print out mocha error message into "output" area

### ISSUE THREAD

**Issue by chigix** [maty21/mocha-sidebar#44]
I saw an error alert emitted in my usage today, but I didn't know why it alerted:

![2017-12-23_22-30-45](https://user-images.githubusercontent.com/2692787/34319968-25d93284-e832-11e7-800f-b90e750c1df5.png)
Until I ran the original `mocha` command I saw the compiling error in the log through the terminal, which is actually also highlighted in the screenshot above. 

So is it possible or is there any options I could use to make the mocha's original log or error messages could be brought out ?

**Comment by jmussman** [comment]
Note the location where it is looking for tests. I'm having the same issue on a Mac, it looks for tests in the directory where Node is installed. There is another report of the same error in the open issues from two days ago, and nobody else mentions any problems about the working directory, so I'm thinking this is a bug introduced in the most recent release 20 days ago?
