### ISSUE TITLE
Better error output

### ISSUE THREAD

**Issue by balexandre** [maty21/mocha-sidebar#48]
I'm getting this in a project:

[![](https://s6.postimg.org/kkaw5iuz5/screenshot_136.png)](https://s6.postimg.org/kkaw5iuz5/screenshot_136.png)

so it says there's an error, and to see the output, but the output is only shows that line ... nothing more.

How can I debug what's going on, so I can make this amazing extension to work? :)

*BTW The extension is working on other projects on the same machine.*

**Comment by maty21** [comment]
This is not really the error and there is opened issue about this, 
According to your problem imo its probably bad configuration or that mocha not running via command 
If you still have a problem send  more details and will try to help you

**Comment by balexandre** [comment]
The message says "See mocha output for more info" ... that's the mocha output window, only says that... How can I show you more detailed error?

and yes, running `mocha` on the terminal window, runs all tests normally

**Comment by maty21** [comment]
duplicate #44
