### ISSUE TITLE
Q: Is there a way to prevent the output window from activating?

### ISSUE THREAD

**Issue by mcquiggd** [maty21/mocha-sidebar#54]
Very happy to have discovered this project, and it's proved to be a good productivity tool.

The only slightly jarring thing, for me personally, is the constant activation and streams of text that appear in the output window. I tend to spend a lot of time in the terminal, and I have to keep switching back to that, only to have mocha-sidebar jump back to the output window.

As there are already indications in a sidebar, and inline in code, it would be great to have an option to disable output / or better still, an option to not automatically switch to the output window, allowing me to chose if I want it displayed or not. Perhaps I have missed an existing option to do so...?

**Comment by mcquiggd** [comment]
P.S It seems there is a setting that extensions can use - `preserveFocus: true` to avoid automatically switching to the output window:

https://github.com/Microsoft/vscode/issues/31474

**Comment by maty21** [comment]
Tks for your contribution . we will check it.
BTW since you know how to solve it, the fastest way and if you want :)  is
to create a PR that adds configuration for disabling it.  and we will
approve it ASAP

**Comment by ehartford** [comment]
Yes please, I very much need this feature.  Super annoying for the output window to open every time I save a file.

**Comment by maty21** [comment]
I'll try to add configuration during the weekend

**Comment by mcquiggd** [comment]
@maty21 That would be great. It's Carnival time where I live, so I wouldn't have time to look at it this week. If you do need help I can revisit next week (although probably hungover).

Either way, perhaps I can contribute.
