### ISSUE TITLE
Can't debug with Typescript

### ISSUE THREAD

**Issue by ehartford** [maty21/mocha-sidebar#58]
I can't debug with Typescript.  I set a breakpoint and it seems to be ignored.

Here is my config:

    "mocha.files.glob": "src/**/*.spec.ts",
    "mocha.runTestsOnSave": "true",
    "mocha.requires": [
        "ts-node/register"
    ],
    "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    }

**Comment by maty21** [comment]
Did you install typescript locally ?

**Comment by maty21** [comment]
I'm closing it for now
