### ISSUE TITLE
Mocha sidebar continually seeks tests in not expected location

### ISSUE THREAD

**Issue by rhdandoyle** [maty21/mocha-sidebar#59]
I continually get this message in my console:
"Finding tests with Mocha on Node.js at "/home/someone/.nvm/versions/node/v8.9.4/bin/node"

I suspect this is a message from mocha-sidebar automatically importing tests.

Where is the info coming from to introspect the above path for tests? Can I fix this error? Can I disable looking for tests outside of the local project? I am not using node 8.9.4 when I am in my console.

I stink at unix so please do not make fun :P.

By the way, thank you so much for MS.

**Comment by maty21** [comment]
I should remove the message btw there's already issue about this message.
 anyway mocha sidebar looking for test only where you configured it.
I'm closing it if you have any other problem except this message feel free to reopen it again tks

**Comment by rhdandoyle** [comment]
Sorry for the late notice...no problem. I was not sure this was related to
another issue. I saw issues around not locating files. This is just an
error message with no impact other than noise in my console.

Thanks for the quick turnaround.
