### ISSUE TITLE
Debugging a test causes test to be run twice

### ISSUE THREAD

**Issue by jreina** [maty21/mocha-sidebar#60]
When debugging tests with a breakpoint set, the test is actually run twice. I first noticed this when writing integration tests at work and it has become more of an issue recently.

I have created [a repository](https://github.com/jreina/mocha-sidebar-double-run/blob/master/test/main.spec.js) to reproduce the issue.

Setting a breakpoint on line 8 of `./test/main.spec.js` ([here](https://github.com/jreina/mocha-sidebar-double-run/blob/master/test/main.spec.js#L8)) and debugging the test with mocha-sidebar causes two files to be written even though I only requested one debugging run.

**Comment by maty21** [comment]
Yeah you right I did as a workaround for updating the status cos when it runs via dubbuging I have know way to know what is the test result

**Comment by jreina** [comment]
Just to clarify, you're saying there are two consecutive runs occurring. One with the debugger attached to do the requested action (debug test), and one without the debugger attached to catch the test status?

**Comment by maty21** [comment]
Yeah exactly.
Sorry for that I know that is not perfect but I couldn't find better
solution if you have one I will be more than happy to hear

**Comment by jreina** [comment]
I am looking into it.

**Comment by jreina** [comment]
In my local copy, I am passing in a no-op function as the second parameter to `debugAll`, `debugLevel`, and `debugItem` to resolve the issue for now. Perhaps the `functionOnTerminate` can be decided based on a configuration flag? Something like 
```javascript
const noop = function() {};

debugIteml(element, config.sideBarOptions().showDebugTestStatus ? _mochaProvider.runTest : noop);
```

**Comment by jreina** [comment]
I know not everyone will feel the same, but I generally do not care whether a test passes or fails when I am debugging a test. As I am stepping through the execution, I will already have an idea of whether or not the test will succeed.

**Comment by maty21** [comment]
Ok I can add option for this

**Comment by maty21** [comment]
Btw you can do it as well just create a PR if you like

On Feb 14, 2018 8:21 PM, "maty zisserman" <maty21@gmail.com> wrote:

Ok I can add option for this

**Comment by jreina** [comment]
Thanks for the merge. I will follow up soon with tests and documentation on the new option. I updated the extension at work and it is working as expected.
