### ISSUE TITLE
Why I get multiple 'Finding tests with Mocha on Node.js at "C:\Program Files\nodejs\node.EXE"' in output?

### ISSUE THREAD

**Issue by antonpegov** [maty21/mocha-sidebar#62]
And tests results are not refreshing after changing the code, is it normal behavior?
[screenshot](http://joxi.ru/DmBJWMBcNaMyxm)

**Comment by maty21** [comment]
About the first thing it just incorrect message you should igonre it.

About the not refreshing test , tests should be updated after changing

**Comment by maty21** [comment]
remove messages in 0.14.30
