### ISSUE TITLE
Support custom mocha binary

### ISSUE THREAD

**Issue by joefiorini** [maty21/mocha-sidebar#70]
We use electron-mocha to handle DOM-based rendering for react testing. It would be nice if I could specify a custom mocha binary in the mocha-sidebar config to be able to run these tests in vscode. Can I do this via `nodeOptions` or is this something you might accept a PR for?

**Comment by maty21** [comment]
We will more than happy to accept any kind of PR :)

**Comment by maty21** [comment]
Im working on it hope to add it until the weekend

**Comment by maty21** [comment]
fixed for 0.14.30

**Comment by enguerran** [comment]
I tried to add in `settings.json` 
```
"mocha.path": "../node_modules/electron-mocha"
```

And `mocha-sidebar` is
```
trying to searching for tests using these settings: 

    mocha path: ../node_modules/electron-mocha/lib/mocha.js
```

But there is no such `lib/mocha.js` in `node_modules/electron-mocha`, `mocha.js` is located on the root folder of `node_modules/electron-mocha` ([electron-mocha 6.0.4](https://github.com/jprichardson/electron-mocha))

**Comment by maty21** [comment]
I see it's an issue coz right I'm adding this suffix always. there's couple
if PR about mocha path so I should decide what is the best approach to
tackle this issue. as a workaround  until I'll fix it .you can create  a
new file under lib/mocha.js that requires the correct path or something
like that
