### ISSUE TITLE
Show sidebar outline for tests written with Jest

### ISSUE THREAD

**Issue by simon-johansson** [maty21/mocha-sidebar#77]
Hello, first of all, great job with the extension!

Even without the functionality of running and debugging tests I think its awesome to just have an outline of the tests suite in the sidebar, helps a lot with navigation. I am using Jest at the moment and would like to have the same awesomeness in that project (Jest also uses the "describe" and "it" statements). 

Is there any configuration I can do to not run the tests but to only show the outline in the sidebar?

If not, I am thinking of making a fork and stripping this extension down to just showing the test suite outline and be able to navigate to individual tests. I think some other people might find that useful as well. Do you think this is doable without to much effort? Any pointers of were I should start looking?

**Comment by maty21** [comment]
first thanks, currently you cant navigate using jest.
 it's on my roadmap to support jest.
 if you want we can work together on that feature :)

Maty Z

**Comment by simon-johansson** [comment]
Great to hear that it is in the roadmap!
Adding Jest support sounds like quite a big undertaking, I was hoping for a quick-and-dirty solution 😁

**Comment by simon-johansson** [comment]
I ended up writing a dedicated mapper for the vs code extension [CodeMap](https://marketplace.visualstudio.com/items?itemName=oleg-shilo.codemap). Seems to work so far.
Gist can be found here: https://gist.github.com/simon-johansson/3be2f96affd6e152d371d18fb96ed362

**Comment by maty21** [comment]
Seems to be nice extension thanks for your supporting
