### ISSUE TITLE
Getting "Failed to run Mocha due to artifacts is not defined" after installing extension

### ISSUE THREAD

**Issue by PriZnaK** [maty21/mocha-sidebar#78]
I just have installed the extension, but getting error "Failed to run Mocha due to artifacts is not defined".
Can you help me to fix it? Screenshot:

![fullsizeoutput_25d6](https://user-images.githubusercontent.com/36400865/37241853-b0a5b294-2468-11e8-8b3d-d60f7a0a9543.jpeg)

**Comment by maty21** [comment]
It's seems like there is a problem in your code
Can you run it from the cli

**Comment by PriZnaK** [comment]
Everything works fine when I run "npm run test". I get all test results.

**Comment by maty21** [comment]
Open mocha output from the output panel you should see the exception

**Comment by PriZnaK** [comment]
Thanks, it helped!

<img width="875" alt="2018-03-10 17 54 57" src="https://user-images.githubusercontent.com/36400865/37244087-66c1eafc-248c-11e8-9b4a-c39340e25318.png">

error in line:
const Debts = artifacts.require('./Debts.sol'); 

something wrong with paths... will try to figure out...

**Comment by maty21** [comment]
I'm closing it for now please feel free to reopen it again

**Comment by PriZnaK** [comment]
many thanks!
