### ISSUE TITLE
Messages don't output.

### ISSUE THREAD

**Issue by screamcha** [maty21/mocha-sidebar#83]
My tests pass/fail as needed, but I can't see any messages in the output window. I have my tests in task/app.spec.js file. I chose "Mocha" among the output windows.
It may be the issue with my vscode configurations. In either case be glad to have a solution on this. Thanks!

**Comment by maty21** [comment]
Did you use the default mocha sidebar configuration if  not please add it to the issue description  thanks

**Comment by screamcha** [comment]
@maty21 I use default configurations. Nothing is changed.

**Comment by liwb** [comment]
@screamcha try this option
"mocha.logVerbose": true

**Comment by scorpiodawg** [comment]
It seems [this commit](https://github.com/maty21/mocha-sidebar/commit/76305da4fd5feb0abea4befbab6e05f3129544d7) broke/changed output. I'm able to see output if I set `"mocha.logVerbose": true` but then the output is not colored and just looks like log output (not sure if the default Mocha coloring is supposed to show in the output).

What is the correct fix for this? Or is this as designed?

**Comment by maty21** [comment]
You right in order to see logs you should set logVerbose to true 
It impossible to color it since vscode output not support it yet

**Comment by screamcha** [comment]
`"mocha.logVerbose": true` is really working. Thanks for help.
