### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by mrdulin** [maty21/mocha-sidebar#89]
### Description

I want to uninstall this extension. 

#### Steps to Reproduce

https://ws2.sinaimg.cn/large/006tKfTcgy1fq0g69zekxg30z50iohdu.gif

#### Expected Results

when reload vscode, it should be uninstalled!

#### Actual Results

when reload vscode, it's not uninstalled!

#### Settings file

default settings

### Versions

- VScode: 1.21.1 (1.21.1)
- Mocha SideBar: v0.17.5

### OS version

- [ ] Linux 
- [x] Mac
- [ ] Windows

#### Example for reproducing

see the gif image

**Comment by yehiyam** [comment]
Closing the issue for now. @mrdulin feel free to reopen if you still have problems
