### ISSUE TITLE
Multiple mocha.requires don't auto add -r flag

### ISSUE THREAD

**Issue by 7sDream** [maty21/mocha-sidebar#94]
### Description

Use two `requires` in configure will broke test runner

#### Steps to Reproduce

Configure mocha sidebar with:

```json
"mocha.files.glob": "tests/**/*.ts",
"mocha.requires": [
    "ts-node/register",
    "tsconfig-paths/register"
],
```

Then run a test in debug mode

#### Expected Results

Run test successfully

#### Actual Results

The log shows command be executed is:

`path/to/node inspect-brk=45522 path/to/_mocha tests/**/*.ts --grep '^<test description>$' -r ts-node/register tsconfig-paths/register`

Notice missing `-r` before `tsconfig-paths/register`

Error message:

```
Debugger listening on ws://127.0.0.1:46258/a1706662-66a5-4345-9ebf-ece475426217
Debugger attached.
/home/username/.vscode/extensions/maty.vscode-mocha-sidebar-0.17.5/node_modules/mocha/lib/utils.js:634
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
              ^
Error: cannot resolve path (or pattern) 'tsconfig-paths/register'
```

#### Settings file

```json
"mocha.files.glob": "tests/**/*.ts",
"mocha.requires": [
    "ts-node/register",
    "tsconfig-paths/register"
],

```

### Versions

- VScode: v1.22.2
- Mocha SideBar: v0.17.5
- Node Version: v9.11.1

### OS version

- [x] Linux 
- [ ] Mac
- [ ] Windows

#### Example for reproducing

N/A

---

My workaround

```json
"mocha.requires": [
    "ts-node/register",
    "-r",
    "tsconfig-paths/register",
],
```

Update: add `-r` seem break scanning and normal running, no `-r` break debug mode running...

**Comment by yehiyam** [comment]
fixed in version 0.17.6
