### ISSUE TITLE
typescript documentation error

### ISSUE THREAD

**Issue by YousefED** [maty21/mocha-sidebar#96]
With latest version, this doesn't work for me (which is copy pased from docs):

```
"mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    },
```
But this does:

```
"mocha.options": {
        "compilers": "ts:ts-node/register"
    },
```

**Comment by liwb** [comment]
+1, same error

**Comment by maty21** [comment]
close in version 0.18.1   in commit [4997c672ae54561310fee0db357441bd348c190d](https://github.com/maty21/mocha-sidebar/commit/4997c672ae54561310fee0db357441bd348c190d#diff-04c6e90faac2675aa89e2176d2eec7d8)
