### ISSUE TITLE
Test titles interpreted as regular expression while debugging.

### ISSUE THREAD

**Issue by jreina** [maty21/mocha-sidebar#99]
### Description
If a test title contains RegEx tokens, the test is not run when clicking the debug icon in Mocha Sidebar.

#### Steps to Reproduce

Try to debug the following with Mocha Sidebar:
```javascript
describe('test', function() {
    it('Should not be [a-z] interpreted as a regex', function() {
      expect(1 + 1).to.equal(2);
    });
});
```

#### Expected Results

The debug console in VS Code should show the test spec title and description, and the test should run.

#### Actual Results

The debug console does not show spec title nor description, and test is not run.

#### Settings file

<!-- Example: {
```
  "mocha.files.glob": "test/**/*.js",
  "mocha.sideBarOptions": {
      "lens": true,
      "decoration": true,
      "autoUpdateTime": 2000,
      "showDebugTestStatus": true
  }
}
``` -->
```
```


### Versions

- VScode: v1.22.2
- Mocha SideBar: v0.17.8
- Node Version: v10.0.0


### OS version
<!-- Check all that apply -->
- [ ] Linux 
- [ ] Mac
- [x] Windows



#### Example for reproducing
<!-- path for github project -->
<!-- https://github.com/maty21/mocha-sidebar/tree/master/test/workspace -->
<!-- ...or provide your own repro URL -->
```javascript
describe('test', function() {
    it('Should not be [a-z] interpreted as a regex', function() {
      expect(1 + 1).to.equal(2);
    });
});
```

**Comment by jreina** [comment]
As an aside, I bug you a lot about issues with the sidebar. I am a test engineer and I use the sidebar all day every day. I have limited spare time, but I will contribute to this project as often as I can since it is such a valuable tool for me. Additionally, I want to thank you for creating this tool.

**Comment by maty21** [comment]
@jreina  tks for your support your warming words its something that drives us to continue contributing tks man
